</div><!-- /pq-main-wrapper -->
</div><!-- /pq-hero-bg-wrap (100% 파란색 배경 끝) -->

<!-- 하단 배너 (1440px) -->
<section class="pq-container-1440 pq-main-banner-wrap">
    <div class="pq-main-banner">
            <img src="/path/html/layout/img/main/banner_01.jpg" alt="지금 바로 PQ문어다리를 경험해보세요!" usemap="#banner_01-map"/>
    </div>
</section>

<!-- 배너 ~ 푸터 사이 여백 (114px) -->
<div class="pq-gap-114"></div>

<!-- 푸터 (Bottom 1px 라인 100% + 1440px 중앙 정렬) -->
<footer class="pq-footer-wrap">
    <div class="pq-container-1440 pq-footer-content">
        <div class="pq-footer-img">
            <img src="/path/html/layout/img/main/bottom.jpg" alt="PQ Octopus DSL Footer Navigation" />
        </div>
    </div>
</footer>
<map name="swf_n02-map">
    <area target="_self" alt="pq최선버젼다운로드" title="pq최선버젼다운로드" href="/path/02/" coords="1110,53,1316,104" shape="rect">
</map>
<map name="banner_01-map">
    <area target="_self" alt="무료다운로드" title="무료다운로드" href="/path/02/" coords="955,46,1140,89" shape="rect">
    <area target="_self" alt="예제보기" title="예제보기" href="/path/06/" coords="1155,44,1344,91" shape="rect">
</map>
</body>
</html>