<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
	<meta name="description" content="description">
    <title>TITLE </title>
    <link rel="stylesheet" href="/path/assets/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="/path/assets/icons/bootstrap-icons.min.css">
    <link rel="stylesheet" href="/path/assets/css/base.css">
    <style>
        body { -webkit-tap-highlight-color: transparent; background-color: #f8f9fa; }
        .pq-app-body { padding-top: 56px; padding-bottom: 60px; }
    </style>
</head>
<body>
<div class="container-fluid pq-app-body">
