<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <title>PQ Mobile [[=$version]]</title>
    <!-- 로컬 벤더 자원 고속 로드 -->
    <link rel="stylesheet" href="[[=PQ_BASE]]/assets/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="[[=PQ_BASE]]/assets/icons/bootstrap-icons.min.css">
    <link rel="stylesheet" href="[[=PQ_BASE]]/assets/css/base.css">
    <style>
        body { -webkit-tap-highlight-color: transparent; background-color: #f8f9fa; }
        .pq-app-body { padding-top: 56px; padding-bottom: 60px; } /* 상하단 바 공간 확보 */
    </style>
</head>
<body>
<div class="container-fluid pq-app-body">
